app/urls.py
from django.urls import path
from app import views

app_name = "app"

urlpatterns = [
    path('', views.index, name="index"),
    path('home', views.home, name="home"),
    path('employees', views.employees, name="employees"),
    path('search_employees', views.search_employees, name='search_employees'),
    path('dns_lookup', views.dns_lookup, name='dns_lookup'),
]

django_security/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup', views.signup, name="signup"),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('change_password', auth_views.PasswordChangeView.as_view(), name='change_password'),
    path('password_change_done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(),
    name='password_reset_done'),
    path('password_reset_confirm/<slug:uidb64>/<slug:token>/', auth_views.PasswordResetConfirmView.as_view(),
    name='password_reset_confirm'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(),
    name='password_reset_complete'),
    path('',include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    emp_id = models.IntegerField()
    first_name = models.CharField(max_length = 1000)
    last_name = models.CharField(max_length = 1000)
    age = models.IntegerField()
    sex = models.CharField(max_length = 100)
    department = models.CharField(max_length = 1000)
    designation = models.CharField(max_length = 1000)

    def __str__(self):
        return self.first_name

class Blog(models.Model):
    name = models.CharField(max_length = 1000)
    author = models.CharField(max_length = 1000)
    price = models.CharField(max_length = 1000)

    def __str__(self):
        return self.name

app/forms.py
from django import forms
from app.models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'

app/views.py
from django.shortcuts import render, redirect
from app.models import Employee, Blog
from app.forms import BlogForm
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.db import connection
import subprocess, shlex
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, "app/index.html")

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, "New user created! Please sign in.")
            return redirect('app:index')
    else:
        form = UserCreationForm()

    return render(request, "registration/signup.html", {"form":form})

@login_required
def home(request):
    return render(request, "app/home.html")

@login_required
def employees(request):
    if request.method == "POST":
        emp_id = request.POST.get("emp_id")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        age = request.POST.get("age")
        sex = request.POST.get("sex")
        department = request.POST.get("department")
        designation = request.POST.get("designation")

        # Saving to DB using Django ORM - the best way
        Employee.objects.create(emp_id=emp_id, first_name=first_name, last_name=last_name,
        age=age, sex=sex, department=department, designation=designation)

        # # Direct SQL Queries - the wrong way
        # cursor = connection.cursor()
        # query = "INSERT INTO app_employee (emp_id, first_name, last_name, age, sex, department, designation) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s')" % (emp_id, first_name, last_name, age, sex, department, designation)
        # cursor.execute(query)

        # # Direct SQL Queries - the correct way
        # cursor = connection.cursor()
        # cursor.execute("INSERT INTO app_employee (emp_id, first_name, last_name, age, sex, department, designation) VALUES (%s, %s, %s, %s, %s, %s, %s)", [emp_id, first_name, last_name, age, sex, department, designation])

        return redirect("app:employees")
    else:
        # Fetch all employees using Django ORM
        employees = Employee.objects.all()

        return render(request, 'app/employees.html',
        {"employees":employees})

@login_required
@csrf_exempt
def search_employees(request):
    if request.is_ajax():
        search_term = request.POST.get('searchTerm')

        # Searching employees using Django ORM - the best way
        employees = Employee.objects.filter(first_name__icontains=search_term)

        # # Searching employees using raw() - the wrong way
        # query = "SELECT * FROM app_employee WHERE first_name ILIKE '%s';" % search_term
        # employees = Employee.objects.raw(query)

        # # Searching employees using raw() - the correct way
        # employees = Employee.objects.raw('SELECT * FROM app_employee WHERE first_name ILIKE %s;',[search_term])

        # # Searching employees using extra() - the wrong way
        # employees = Employee.objects.extra(where=["first_name ILIKE '%s'" % search_term])

        # # Searching employees using extra() - the correct way
        # employees = Employee.objects.extra(where=['first_name ILIKE %s'], params=[search_term])

        html = render_to_string('app/search_employees.html',
        {'employees':employees})

        return HttpResponse(html)

@login_required
def dns_lookup(request):
    if request.method == "POST":
        domain_name = request.POST.get("domain_name")

        # # DNS Lookup - the wrong way
        # command = "nslookup {}".format(domain_name)
        # output = subprocess.check_output(command, shell=True, encoding='UTF-8')
        # return render(request, 'app/dns_lookup.html', {'output':output,
        # 'domain_name':domain_name})

        # # DNS Lookup - the better way
        # try:
        #     safe_domain_name = shlex.quote(domain_name)
        #     command = "nslookup {}".format(safe_domain_name)
        #     output = subprocess.check_output(command, shell=True, encoding='UTF-8')
        #
        #     return render(request, 'app/dns_lookup.html', {'output':output,
        #     'domain_name':domain_name})
        # except subprocess.CalledProcessError:
        #     return render(request, 'app/dns_lookup.html', {'output':"Invalid Input",
        #     'domain_name':domain_name})


        # DNS Lookup - the best way - without shell=True
        try:
            raw_command = "nslookup {}".format(domain_name)
            safe_command = shlex.split(raw_command)
            print(safe_command)
            output = subprocess.check_output(safe_command, encoding='UTF-8')

            return render(request, 'app/dns_lookup.html', {'output':output,
            'domain_name':domain_name})
        except subprocess.CalledProcessError:
            return render(request, 'app/dns_lookup.html', {'output':"Invalid Input",
            'domain_name':domain_name})

        ## Note - Avoid using the deprecated os module

    else:
        return render(request, "app/dns_lookup.html")

app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap 5 -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
    crossorigin="anonymous">

    <!-- Fontawesome -->
    <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous">

    <!-- Google Fonts - Nunito -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito" rel="stylesheet">

    <!-- Data Tables -->
    <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">

    <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/select/1.3.3/css/select.bootstrap5.min.css">

    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <style>
      /* To remove the down arrow by the right of the user avatar in the navbar */
      .dropdown-toggle::after {
        content: none;
      }
    </style>

    {% block head %}

    {% endblock %}
  </head>
  <body>
    <!-- Bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous">
    </script>

    <!-- jQuery for Data Tables -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
      integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
      crossorigin="anonymous">
    </script>

    <!-- JS for Data Tables -->
    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js">
    </script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'app:home' %}">djSecurity</a>
        <button class="navbar-toggler" type="button"
        data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false"
        aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page"
              href="{% url 'app:employees' %}">Employees</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page"
              href="{% url 'app:dns_lookup' %}">DNS Lookup</a>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown"
              aria-expanded="true">
                <div class="white-color hover-orange size-24px">
                  <span>{{ user }}</span>
                  <i class="fas fa-user"></i>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-end">
                <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block body %}

    {% endblock %}

  </body>
</html>

app/templates/app/dns_lookup.html
{% extends "app/base.html" %}

{% block head %}
<title>DNS Lookup</title>
{% endblock %}

{% block body %}
<div class="container">
  <h3 class="mt-4 text-center">DNS Lookup</h3>

  <div class="row mt-4">
    <div class="col-md-2"></div>
    <div class="col-md-8 text-center">
      <form method="POST">
        {% csrf_token %}
        <input type="text" class="form-control" name="domain_name"
        placeholder="Domain Name">

        <button class="btn btn-primary mt-2" type="submit">
          <i class="fas fa-search"></i>
          Lookup
        </button>
      </form>
    </div>
    <div class="col-md-2"></div>
  </div>

  <div class="row mt-4">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h5 class="text-center">{{ domain_name }}</h5>
      <p>{{ output }}</p>
    </div>
    <div class="col-md-2"></div>
  </div>

</div>

{% endblock %}

app/templates/app/employees.html
{% extends "app/base.html" %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<div class="container">
  <h3 class="mt-4 text-center">Employees</h3>

  <div class="row mb-2">
    <div class="col-md-6">
      <div style="width:50%;" class="input-group">
        <input id="searchBox" type="text" class="form-control"
        placeholder="Search Employees">
        <button class="btn btn-outline-secondary" type="button" id="searchEmployee">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>

    <div class="col-md-6">
      <div class="float-end">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
        data-bs-target="#addEmployeeModal">
          <i class="fas fa-plus"></i>
          Add
        </button>
      </div>
    </div>
  </div>

  <div id="searchOutput">
    <table id="employeeTable" class="table table-bordered">
      <thead class="table-secondary">
        <tr>
          <th>Emp Code</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Age</th>
          <th>Sex</th>
          <th>Department</th>
          <th>Designation</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in employees %}
        <tr>
          <td>{{ employee.emp_id }}</td>
          <td>{{ employee.first_name }}</td>
          <td>{{ employee.last_name }}</td>
          <td>{{ employee.age }}</td>
          <td>{{ employee.sex }}</td>
          <td>{{ employee.department }}</td>
          <td>{{ employee.designation }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Add Employee Modal -->
  <div class="modal fade" id="addEmployeeModal" tabindex="-1" aria-labelledby="addEmployeeModalLable"
   aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add Employee</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"
          aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-4">
              <input style="width:100%;" name="emp_id" type="text"
              class="form-control mb-2" placeholder="Employee ID" required>

              <input style="width:100%;" name="first_name" type="text"
              class="form-control mb-2" placeholder="First Name" required>

              <input style="width:100%;" name="last_name" type="text"
              class="form-control mb-2" placeholder="Last Name" required>

              <input style="width:100%;" name="age" type="text"
              class="form-control mb-2" placeholder="Age" required>

              <input style="width:100%;" name="sex" type="text"
              class="form-control mb-2" placeholder="Sex" required>

              <input style="width:100%;" name="department" type="text"
              class="form-control mb-2" placeholder="Department" required>

              <input style="width:100%;" name="designation" type="text"
              class="form-control" placeholder="Designation" required>
            </div>

            <button class="btn btn-primary" type="submit" name="button">Save</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>

<!-- JS Function to Search Employee -->
<script type="text/javascript">
  $(document).ready(function() {
    $(document).on("click","#searchEmployee",function() {
      var searchTerm = $("#searchBox").val();

      $.ajax({
          type: "POST",
          url: "{% url 'app:search_employees' %}",
          data: {'searchTerm':searchTerm},
          success: function(response){
            $('#searchOutput').html(response);
          }
      });

    });
  });
</script>

{% endblock %}

app/templates/app/home.html
{% extends "app/base.html" %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
  
{% endblock %}

app/templates/app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap 5 -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
    crossorigin="anonymous">

    <!-- Fontawesome -->
    <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous">

    <!-- Google Fonts - Nunito -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito" rel="stylesheet">

    <!-- Data Tables -->
    <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">

    <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/select/1.3.3/css/select.bootstrap5.min.css">

    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <style>
      /* To remove the down arrow by the right of the user avatar in the navbar */
      .dropdown-toggle::after {
        content: none;
      }
    </style>

  </head>
  <body>
    <!-- Bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous">
    </script>

    <!-- jQuery for Data Tables -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
      integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
      crossorigin="anonymous">
    </script>

    <!-- JS for Data Tables -->
    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js">
    </script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'app:index' %}">djSecurity</a>

      </div>
    </nav>

    <div class="container">
      <div class="mt-2">
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"
            aria-label="Close"></button>
          </div>
          {% endfor %}
        {% endif %}
      </div>
      <div class="card mt-4">
        <div class="card-body text-center">
          <h1>Welcome!</h1>
          <a class="btn btn-secondary" href="{% url 'signup' %}">Sign Up</a>
          <a class="btn btn-primary" href="{% url 'login' %}">Log In</a>
        </div>
      </div>
    </div>

  </body>
</html>

app/templates/app/search_employees.html
<table id="employeeTable" class="table table-bordered">
  <thead class="table-secondary">
    <tr>
      <th>Emp Code</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Department</th>
      <th>Designation</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employees %}
    <tr>
      <td>{{ employee.emp_id }}</td>
      <td>{{ employee.first_name }}</td>
      <td>{{ employee.last_name }}</td>
      <td>{{ employee.age }}</td>
      <td>{{ employee.sex }}</td>
      <td>{{ employee.department }}</td>
      <td>{{ employee.designation }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

templates/bs5_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group mt-3">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}
  </div>
{% endfor %}